### ISSUE TITLE
ツイート取得エラー時のハンドリングができていない

### ISSUE THREAD

**Issue by netebakari** [netebakari/twitter-tl-tracker#2]
鍵アカウントのツイートを取得しようとしたりAPI利用制限に引っかかったときのエラー処理が正しくない。

```
INFO  TwitterClient#getTweets(): endpoint=statuses/user_timeline, parameter=...（鍵アカウント）
ERROR  {
  request: '/1.1/statuses/user_timeline.json',
  error: 'Not authorized.'
}
ERROR  Invoke Error
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'indexOf' of undefined",
    "stack": [
        "TypeError: Cannot read property 'indexOf' of undefined",
        "    at processSingleQueueMessage (/var/task/index.js:214:23)",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

**Comment by netebakari** [comment]
`e.message.indexOf("..")` が間違いっぽい。様子見。

**Comment by netebakari** [comment]
エラー発生時にスローするオブジェクトの形が変わっていたため合わせて修正した
